### PR TITLE
Porting over code from sktime-neuro-draft

### PR DESCRIPTION
**Pull request by SveaMeyer13**
**Changes**

- Adjust flake8 in setup.cfg to be compatible with black for pre-commit hooks
- Add utilities to create mne data format from sktime data format and to create annotations from mne raw object
- Add series-to-series transformers
       - temporal filter
       - downsampling
       - missing: Artifact Removal
- Add panel-to-panel transformers
      - temporal filter
      - downsampling
      - slicing
      - baseline correction
- Add base class for series-to-panel transformer
- Add series-to-panel transformer 
      - epoching
- Add notebook of example notebook
- Add tests 
      - for filterforseries
      - for filterforpanel
      - more to follow, not sure how to port tests from sktime though

**To dos:**

- [ ] add artifact removal
- [ ] add/port tests from sktime

### CODE REVIEW

**Comment by SveaMeyer13** [comment]
It does not seem to find mne as a dependency. Do I need to add it somewhere else other than in the setup.py?

**Comment by TonyBagnall** [comment]
build_tools/requirements.txt perhaps?

**Review by TonyBagnall — APPROVED** [review]
happy to approve this, but for the next you might want to look at adding the docstrings and meta information in the sktime format. Add author at the top, broadly follow goals laid out here https://github.com/alan-turing-institute/sktime/milestone/6

**Comment by TonyBagnall** [comment]
I was looking at one file without so much documentation, I see there is plenty there already. Given this has all been reviewed elsewhere, I will merge it, I find it easier to review in an IDE.

**Pull request merged**
